# Generated by Django 5.1.4 on 2025-12-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='community',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='community',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='historicalcommunity',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='historicalcommunity',
            name='cover_url',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='media',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat_avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='community',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='community_avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='community',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='community_covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='historicalcommunity',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='historicalcommunity',
            name='cover',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/', verbose_name='Файл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/', verbose_name='Миниатюра'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
    ]
